spring.application.name=ms-usuarios
server.port=8090

# URL original del grupo que SÍ conecta al servidor
spring.datasource.url=jdbc:postgresql://ep-fancy-feather-apizlfyv-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_kXlTJLjO5rs6
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate idéntica a la del video del profe
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.enabled=false